#pragma once

  
    /** 
    *   @brief  The different possible events that can be generated by a nav switch and passed to registered callbacks. 
    */
    enum class nav_switch_evt_t 
    {
      quick_press, ///<quick-press event, generated if nav input is pressed, then released before (25ms + nav_switch->nav_switch_conf.long_press_evt_time) elapses
      long_press, ///<long-press event, generated if nav input is pressed, and not released after (25ms + nav_switch->nav_switch_conf.long_press_evt_time) elapses
      held, ///<held event, generated if nav input is held after long-press event has been generated, re-generates every nav_switch->nav_switch_conf->hold_evt_time microseconds until nav input is released 
      released ///<release event, generated when nav input is released (note, nav input release event not generated for quick-press events)
    };